export enum Routers {
  Home = "/",
  Admin = "/admin",
  Login = "/login",
  Error = "/error",
  Reset = "/reset",
  Client = "/client",
  Server = "/server",
  ApiAuth = "/api/auth",
  ApiAdmin = "/api/admin",
  Register = "/register",
  Settings = "/settings",
  NewPassword = "/new-password",
  NewVerification = "/new-verification",
}